### ISSUE TITLE
controlFlow-nonNull demo code not working properly in VsCode

### ISSUE THREAD

**Issue by RandyWilkinson** [Microsoft/typescript-build2016-demos#2]
I opened the controlFlow-nonNull directory with VsCode and added a settings.json to a .vscode directory with the following config:
"typescript.tsdk": "TypeScript-controlFlowTypes"

Yet when i hover over the variables in the programs I am not getting the same results as in the build talk. For instance, when I hover over the x variable in the following code from the union.ts file I get what seems like incorrect results:
if (x instanceof A) {
        x; // hovering over this I get "let x: A | B | C | D | E" 
        x = new B();
        x; // hovering over this I get "let x: A | B | C | D | E" 
    }

I am using the 1.1.0 version of VsCode. I also set the "strictNullChecks" flag to true in tsconfig.json.

**Comment by bowdenk7** [comment]
Can you try closing/reopening any files in the VS Code "working files" section? Perhaps the language service isn't getting reloaded.

![image](https://cloud.githubusercontent.com/assets/820883/15190323/28173c76-1764-11e6-8a87-10ca9d32eb13.png)

**Comment by RandyWilkinson** [comment]
It seems like the language service is loading because I get proper control flow type analysis on the else condtions. Just seems to work inconsistently.
![demo](https://cloud.githubusercontent.com/assets/15603092/15226699/a9199dee-1838-11e6-9f6f-e172f3a27776.png)

**Comment by Mimetis** [comment]
Exact same issue here

**Comment by Mimetis** [comment]
By the way the null.ts demo is not correct in my VS Code :
![nullcheck](https://cloud.githubusercontent.com/assets/4592555/15670952/5abe1662-2728-11e6-8e39-c8832035513c.png)

should be only (string | string[] | null) and not undefined

**Comment by Mimetis** [comment]
any update on this ?

**Comment by bowdenk7** [comment]
If you don't mind, try pulling and giving it another try. I updated the TypeScript that is bundled to our latest nightly build. It's possible there is some bug I missed that we have fixed by now.

**Comment by Mimetis** [comment]
Awesome, it's working perflectly now ! Thx for taking time to resolve this issue :)

**Comment by bowdenk7** [comment]
Great! Let me know if anything else comes up!
